01.Materi.University.Web/Controllers/DosenController.cs
using _02.Materi.University.DataAccess;
using _03.Materi.University.ViewModel;
using _01.Materi.University.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _01.Materi.University.Web.Models.Shared;

namespace _01.Materi.University.Web.Controllers
{
    public class DosenController : Controller
    {
        // GET: Dosen
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List(int? paramPage, int paramPageSize, string paramSearch, int paramAsc, int paramDesc)
        {
            /* for paged */
            int countDataDb = DosenDataAccess.GetCountData(paramSearch);
            PagingModel_Jurusan pg = new PagingModel_Jurusan(countDataDb, paramPage, paramPageSize);
            ViewData["pg"] = pg;

            List<DosenViewModel> listData = DosenDataAccess.GetListAll(paramSearch, paramAsc, paramDesc, ((pg.CurrentPage - 1) * pg.PageSize), pg.PageSize);

            return View("List", listData);

        }
        public ActionResult Create()
        {
            ViewBag.JurusanList = new SelectList(JurusanDataAccess.GetListAll(), "id_jurusan_pk", "nama_jurusan");
            ViewData["TypeDosenList"] = TypeDosenDataAccess.GetListAll();

            return View();
        }
        [HttpPost]
        public ActionResult Create(DosenViewModel paramModel)
        {
            try
            {
                paramModel.created_by = "adit";
                paramModel.created_date = DateTime.Now;
                paramModel.updated_by = "adit";
                paramModel.updated_date = DateTime.Now;
                List<Files> statusUpload = Models.Shared.Helper.FnFileUploadMultiple(Request.Files, Request.Browser.Browser.ToUpper(), "~/Images/");

                if (DosenDataAccess.Insert(paramModel))
                {
                    return Json(new { success = true, message = "Data berhasil ditambahkan!" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = DosenDataAccess.Message }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new { success = true, message = hasError.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Edit(int paramId)
        {
            ViewBag.JurusanList = new SelectList(JurusanDataAccess.GetListAll(), "id_jurusan_pk", "nama_jurusan");
            ViewData["TypeDosenList"] = TypeDosenDataAccess.GetListAll();
            return View(DosenDataAccess.GetDetailsByid(paramId));
        }
        [HttpPost]
        public ActionResult Edit(DosenViewModel paramModel)
        {
            try
            {
                paramModel.updated_by = "adit";
                paramModel.updated_date = DateTime.Now;

                if (DosenDataAccess.Update(paramModel))
                {
                    return Json(new { success = true, message = "Data berhasil ditambahkan!" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = true, message = DosenDataAccess.Message }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new { success = true, message = hasError.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Details(int paramId)
        {
            return View(DosenDataAccess.GetDetailsByid(paramId));
        }


        [HttpPost]
        public ActionResult UploadFiles(DosenViewModel paramModel)
        {
            // Checking no of files injected in Request object  
            if (Request.Files.Count > 0)
            {
                List<Files> statusUpload = Models.Shared.Helper.FnFileUploadMultiple(Request.Files, Request.Browser.Browser.ToUpper(), "~/Images/");
                return Json(new { success = true, message = "sukses" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, message = "gagal" }, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

01.Materi.University.Web/Views/Dosen/Create.cshtml
@using _03.Materi.University.ViewModel;
@model _03.Materi.University.ViewModel.DosenViewModel
@{
    List<TypeDosenViewModel> _typeDosenList = (List<TypeDosenViewModel>)ViewData["TypeDosenList"];
}

<div class="modal-body">
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.kode_dosen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kode_dosen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kode_dosen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nama_dosen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nama_dosen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nama_dosen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_jurusan_fk, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.id_jurusan_fk, (IEnumerable<SelectListItem>)ViewBag.JurusanList, "--- Pilih ---", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_jurusan_fk, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_type_dosen_fk, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="id_type_dosen_fk" id="id_type_dosen_fk" class="form-control">
                    <option class="-" value="">-- Pilih --</option>
                    @{
                        if (_typeDosenList.Count > 0)
                        {
                            foreach (TypeDosenViewModel item in _typeDosenList)
                            {
                                <option class="cursor-1" value="@item.id_type_dosen_pk.ToString().Trim()">
                                    @item.deskripsi
                                </option>
                            }
                        }
                    }
                </select>
                @*@Html.ValidationMessageFor(model => model.id_type_dosen_fk, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.is_active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.is_active)
                @Html.ValidationMessageFor(model => model.is_active, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Upload Foto
            <div class="col-md-10">
                <input type="file" id="FileUpload1" class="form-control" />
                <input type="button" id="btnUpload" value="Upload Files" />

                <button typeof="button" id="btn-add-file" class="btn btn-success" title="Upload File">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Upload File
                </button>
            </div>
        </div>

    </div>
</div>

<div class="modal-footer">
    <input type="button" value="Save" title="Save" class="btn btn-primary" id="btn_create_save" />
    <input type="button" value="Cancel" title="Cancel" class="btn btn-default" id="btn_create_cancel" data-dismiss="modal" />
</div>

<script>
    $("#btn_create_save").click(function () {
        var item = {
            id_dosen_pk: 0,
            kode_dosen: $("#kode_dosen").val().toUpperCase(),
            nama_dosen: $("#nama_dosen").val(),
            id_jurusan_fk: $("#id_jurusan_fk").val(),
            id_type_dosen_fk: $("#id_type_dosen_fk").val(),
            is_active: $("#is_active").is(":checked")
        };
        //alert(JSON.stringify(item));

        $.ajax({
            url: '@Url.Action("Create", "Dosen")',
            type: 'post',
            data: { paramModel: item },
            success: function (result) {
                if (result.success) {
                    $("#modal-edit-form").modal("hide");
                    ShowList();
                }
                else {
                    alert(result.message);
                }
            }
        });
    });

    $("#btn-add-file").click(function () {
        var item = {
            id_dosen_pk: 0,
            kode_dosen: $("#kode_dosen").val().toUpperCase(),
            nama_dosen: $("#nama_dosen").val(),
            id_jurusan_fk: $("#id_jurusan_fk").val(),
            id_type_dosen_fk: $("#id_type_dosen_fk").val(),
            is_active: $("#is_active").is(":checked")
        };
        debugger;

        // Checking whether FormData is available in browser
        if (window.FormData !== undefined) {
            var fileUpload = $("#FileUpload1").get(0);
            var files = fileUpload.files;
            // Create FormData object
            var fileData = new FormData();
            // Looping over all files and add it to FormData object
            for (var i = 0; i < files.length; i++) {
                fileData.append(files[i].name, files[i]);
            }

            // Adding one more key to FormData object
            //fileData.append('username', 'Manas');

            $.ajax({
                url: '/Dosen/UploadFiles',
                type: "POST",
                contentType: false, // Not to set any content header
                processData: false, // Not to process data
                data: fileData,
                enctype: 'multipart/form-data',
                success: function (result) {
                    alert(result.message);
                }
            });
        } else {
            alert("FormData is not supported.");
        }
        });

</script>

01.Materi.University.Web/Views/Dosen/Details.cshtml
@model _03.Materi.University.ViewModel.DosenViewModel

<div class="modal-body">
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.kode_dosen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kode_dosen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nama_dosen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nama_dosen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.id_jurusan_fk)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.program_studi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.id_type_dosen_fk)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status_karyawan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.is_active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.is_active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.updated_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.updated_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.updated_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.updated_date)
        </dd>

    </dl>
</div>

<div class="modal-footer">
    <input type="button" value="Edit" title="Edit" class="btn btn-primary" id="btn_details_edit" data-id="@Html.DisplayFor(model => model.id_dosen_pk)" />
    <input type="button" value="Cancel" title="Cancel" class="btn btn-default" id="btn_create_cancel" data-dismiss="modal" />
</div>

<script>
    $("#btn_details_edit").click(function () {
        $(".modal-title").html("Edit Form Agama");
        $(".div-bind-content").html(progHtml);

        $.ajax({
            url: '@Url.Action("Edit", "Dosen")',
            type: 'get',
            data: { paramId: $(this).attr("data-id") },
            success: function (result) {
                $(".div-bind-content").html(result);
            }
        });

    });
</script>

01.Materi.University.Web/Views/Dosen/Edit.cshtml
@model _03.Materi.University.ViewModel.DosenViewModel
@using _03.Materi.University.ViewModel;
@{
    List<TypeDosenViewModel> _typeDosenList = (List<TypeDosenViewModel>)ViewData["TypeDosenList"];
}

<div class="modal-body">
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_dosen_pk)

        <div class="form-group">
            @Html.LabelFor(model => model.kode_dosen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kode_dosen, new { maxlength = 50, htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kode_dosen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nama_dosen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nama_dosen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nama_dosen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_jurusan_fk, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.id_jurusan_fk, (IEnumerable<SelectListItem>)ViewBag.JurusanList, "--- Pilih ---", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_jurusan_fk, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_type_dosen_fk, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownListFor(model => model.id_type_dosen_fk, (IEnumerable<SelectListItem>)ViewBag.TypeDosenList, "--- Pilih ---", new { @class = "form-control" })*@
                <select name="id_type_dosen_fk" id="id_type_dosen_fk" class="form-control">
                    <option class="-" value="">-- Pilih --</option>
                    @{
                        if (_typeDosenList.Count > 0)
                        {
                            foreach (TypeDosenViewModel item in _typeDosenList)
                            {
                                if (@item.id_type_dosen_pk.ToString().Trim() == @Model.id_type_dosen_fk.ToString().Trim())
                                {
                                    <option class="cursor-1" value="@item.id_type_dosen_pk.ToString().Trim()" selected>@item.deskripsi</option>
                                }
                                else
                                {
                                    <option class="cursor-1" value="@item.id_type_dosen_pk.ToString().Trim()">@item.deskripsi</option>
                                }
                            }
                        }
                    }
                </select>
                @Html.ValidationMessageFor(model => model.id_type_dosen_fk, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.is_active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.is_active)
                @Html.ValidationMessageFor(model => model.is_active, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
</div>


<div class="modal-footer">
    <input type="button" value="Save" title="Save" class="btn btn-primary" id="btn_edit_save" />
    <input type="button" value="Cancel" title="Cancel" class="btn btn-default" id="btn_edit_cancel" data-dismiss="modal" />
</div>

<script>
    $("#btn_edit_save").click(function () {
        validation();
        debugger;
        if (msgDosen != null) {
            alert(msgDosen);
        }
        else {
            var item = {
                id_dosen_pk: $("#id_dosen_pk").val(),
                kode_dosen: $("#kode_dosen").val().toUpperCase(),
                nama_dosen: $("#nama_dosen").val(),
                id_jurusan_fk: $("#id_jurusan_fk").val(),
                id_type_dosen_fk: $("#id_type_dosen_fk").val(),
                is_active: $("#is_active").is(":checked")
            };
            //alert(JSON.stringify(item));

            $.ajax({
                url: '@Url.Action("Edit", "Dosen")',
                type: 'post',
                data: { paramModel: item },
                success: function (result) {
                    if (result.success) {
                        $("#modal-edit-form").modal("hide");
                        ShowList();
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        }
    });

    var msgDosen = null;
    function validation() {
        msgDosen = null;
        if ($("#kode_dosen").val().toUpperCase() == null || $("#kode_dosen").val().toUpperCase() == "") {
            msgDosen += "Kode tidak boleh kosong";
        }

        if ($("#nama_dosen").val().toUpperCase() == null || $("#nama_dosen").val().toUpperCase() == "") {
            msgDosen += "Nama tidak boleh kosong";
        }
    }
</script>

01.Materi.University.Web/Views/Dosen/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Master Data Dosen</h4>

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">

            <button typeof="button" id="btn-add-dosen" class="btn btn-success" title="Create New">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Tambah Data
            </button>

        </div>
        <div class="panel-body">

            <div id="table-list">
                <div class="progress progress-striped active" style="margin-bottom:0">
                    <div class="progress-bar" style="width:100%" />
                </div>
            </div>

        </div>
    </div>
</div>


<div id="modal-edit-form" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
            </div>

            <div class="div-bind-content">
                @*berisikan konten body dan footer*@
            </div>

        </div>

    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        var progHtml = '<div class="progress progress-striped active" style="margin-bottom:0"><div class="progress-bar" style="width:100%"/></div></div>';
        var Last_Record_Per_Page;

        $(document).ready(function () {
            ShowList(1, "", 1, 0);




        });

        function ShowList(pPage, pSearch, pAsc, pDesc) {
            Last_Record_Per_Page = $("#paging-size").val() == undefined ? 5 : $("#paging-size").val();
            $("#table-list").html(progHtml);

            $.ajax({
                url: '@Url.Action("List","Dosen")',
                type: 'get',
                data: { paramPage: pPage, paramPageSize: Last_Record_Per_Page, paramSearch: pSearch, paramAsc: pAsc, paramDesc: pDesc },
                success: function (result) {
                    $("#paging-size").val(Last_Record_Per_Page);
                    $("#table-list").html(result);
                }
            });
        };

        $("#btn-add-dosen").click(function () {
            /* Configurations Modal */
            $("#modal-edit-form").modal("show");
            $(".modal-title").html("Edit Form Dosen");
            $(".div-bind-content").html(progHtml);

            /* Show body modal */
            $.ajax({
                url: '@Url.Action("Create","Dosen")',
                type: 'get',
                success: function (result) {
                    $(".div-bind-content").html(result);
                }
            })
        });

        

    </script>
}

01.Materi.University.Web/Views/Dosen/List.cshtml
@model IEnumerable<_03.Materi.University.ViewModel.DosenViewModel>
@using _03.Materi.University.ViewModel;
@{
    PagingModel_Jurusan _page = (PagingModel_Jurusan)ViewData["pg"];
}


<table style="background-color:ghostwhite; width:100%">
    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr class="tr">
                <td colspan="2"><b>@item.nama_dosen</b></td>
                <td rowspan="5" align="center" style="width:20%; vertical-align:middle">
                    <button title="Edit" class="btn_grid_edit btn btn-warning" data-id="@item.id_dosen_pk">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    </button>
                    <button title="Delete" class="btn_grid_details btn btn-info" data-id="@item.id_dosen_pk">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                    </button>
                </td>
            </tr>
            <tr class="tr">
                <td style="width: 20%">@Html.DisplayNameFor(model => model.kode_dosen)</td>
                <td>@Html.DisplayFor(modelItem => item.kode_dosen)</td>

            </tr>
            <tr class="tr">
                <td>@Html.DisplayNameFor(model => model.id_jurusan_fk)</td>
                <td>@Html.DisplayFor(modelItem => item.program_studi)</td>
            </tr>
            <tr class="tr">
                <td>@Html.DisplayNameFor(model => model.id_type_dosen_fk)</td>
                <td>@Html.DisplayFor(modelItem => item.status_karyawan)</td>
            </tr>
            <tr class="tr">
                <td>@Html.DisplayNameFor(model => model.is_active)</td>
                <td>@Html.DisplayFor(modelItem => item.is_active)</td>
            </tr>

            <tr style="height:25px; background-color:white">
                <td colspan="3"></td>
            </tr>
        }
    }
    <!-- ini buat paging posisi buttom -->
    <tr>
        <td colspan="3">

            <table style="width:100%">
                <tr>
                    @* ini untuk paging *@
                    @if (_page != null)
                    {
                        <td style="float:left">
                            <label>Page @_page.CurrentPage from @_page.TotalPages</label>
                        </td>
                        if (_page.EndPage > 1)
                        {
                            <td>
                                <center>
                                    <ul class="pagination" style="margin:0px">
                                        @if (_page.CurrentPage > 1)
                                        {
                                            <li>
                                                <a href="#" onclick="PagingPageMove(1);">First</a>
                                            </li>
                                            <li>
                                                <a href="#" onclick="PagingPageMove((@_page.CurrentPage - 1));">Previous</a>
                                            </li>
                                        }

                                        @for (var page = _page.StartPage; page <= _page.EndPage; page++)
                                        {
                                            if (page == _page.CurrentPage)
                                            {
                                                <li class="active: active">
                                                    <a href="#" onclick="PagingPageMove(@page);">@page</a>
                                                </li>
                                            }
                                            else
                                            {
                                                <li>
                                                    <a href="#" onclick="PagingPageMove(@page);">@page</a>
                                                </li>
                                            }

                                        }

                                        @if (_page.CurrentPage < _page.TotalPages)
                                        {
                                            <li>
                                                <a href="#" onclick="PagingPageMove(@_page.CurrentPage + 1);">Next</a>
                                            </li>
                                            <li>
                                                <a href="#" onclick="PagingPageMove(@_page.TotalPages);">Last</a>
                                            </li>
                                        }
                                    </ul>
                                </center>
                            </td>
                        }
                    }
                    <td style="float:right">
                        <div class="form-inline">
                            <span>Size</span>&nbsp;
                            <select class="input-xs paged-size" style="height: 25px;" id="paging-size" onchange="PagingPageMove(1)">
                                <option value="5">5</option>
                                <option value="10">10</option>
                                <option value="25">25</option>
                                <option value="50">50</option>
                                <option value="100">100</option>
                            </select>
                        </div>
                    </td>
                </tr>
            </table>

        </td>
    </tr>
</table>

<style>
    .tr {
        height: 25px;
        vertical-align: middle;
    }
</style>

<script type="text/javascript">
    function PagingPageMove(pPage) {
        ShowList(pPage, "", 1, 0);
    };

    $(".btn_grid_edit").click(function () {
        //alert('Id nya adalah :' + $(this).attr("data-id"));
        $("#modal-edit-form").modal("show");
        $(".modal-title").html("Edit Form Dosen");
        $(".div-bind-content").html(progHtml);

        $.ajax({
            url: '@Url.Action("Edit", "Dosen")',
            type: 'get',
            data: { paramId: $(this).attr("data-id") },
            success: function (result) {
                $(".div-bind-content").html(result);
            }
        });
    });

    $(".btn_grid_details").click(function () {
        //alert('Id nya adalah :' + $(this).attr("data-id"));
        $("#modal-edit-form").modal("show");
        $(".modal-title").html("Details Dosen");
        $(".div-bind-content").html(progHtml);

        $.ajax({
            url: '@Url.Action("Details", "Dosen")',
            type: 'get',
            data: { paramId: $(this).attr("data-id") },
            success: function (result) {
                $(".div-bind-content").html(result);
            }
        });
    });

</script>