01.Materi.University.Web/Controllers/TypeDosenController.cs
using _02.Materi.University.DataAccess;
using _03.Materi.University.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _01.Materi.University.Web.Controllers
{
    public class TypeDosenController : Controller
    {
        // GET: TypeDosen
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List()
        {
            return View(TypeDosenDataAccess.GetListAll());
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(TypeDosenViewModel paramModel)
        {
            try
            {
                paramModel.created_by = "adit";
                paramModel.created_date = DateTime.Now;
                paramModel.updated_by = "adit";
                paramModel.updated_date = DateTime.Now;

                if (TypeDosenDataAccess.Insert(paramModel))
                {
                    return Json(new { success = true, message = "Data berhasil ditambahkan!" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = TypeDosenDataAccess.Message }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new { success = true, message = hasError.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Edit(int paramId)
        {
            return View(TypeDosenDataAccess.GetDetailsByid(paramId));
        }
        [HttpPost]
        public ActionResult Edit(TypeDosenViewModel paramModel)
        {
            try
            {
                paramModel.updated_by = "adit";
                paramModel.updated_date = DateTime.Now;

                if (TypeDosenDataAccess.Update(paramModel))
                {
                    return Json(new { success = true, message = "Data berhasil ditambahkan!" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = true, message = TypeDosenDataAccess.Message }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new { success = true, message = hasError.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Details(int paramId)
        {
            return View(TypeDosenDataAccess.GetDetailsByid(paramId));
        }

    }
}

01.Materi.University.Web/Views/TypeDosen/Create.cshtml
@model _03.Materi.University.ViewModel.TypeDosenViewModel

<div class="modal-body">
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.kode_type_dosen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kode_type_dosen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kode_type_dosen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.deskripsi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.deskripsi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.deskripsi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.is_active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.is_active)
                @Html.ValidationMessageFor(model => model.is_active, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
</div>

<div class="modal-footer">
    <input type="button" value="Save" title="Save" class="btn btn-primary" id="btn_create_save" />
    <input type="button" value="Cancel" title="Cancel" class="btn btn-default" id="btn_create_cancel" data-dismiss="modal" />
</div>

<script>
    $("#btn_create_save").click(function () {
        var item = {
            id_type_dosen_pk: 0,
            kode_type_dosen: $("#kode_type_dosen").val().toUpperCase(),
            deskripsi: $("#deskripsi").val(),
            is_active: $("#is_active").is(":checked")
        };

        $.ajax({
            url: '@Url.Action("Create", "TypeDosen")',
            type: 'post',
            data: { paramModel: item },
            success: function (result) {
                if (result.success) {
                    $("#modal-edit-form").modal("hide");
                    ShowList();
                }
                else {
                    alert(result.message);
                }
            }
        });
    });
</script>

01.Materi.University.Web/Views/TypeDosen/Details.cshtml
@model _03.Materi.University.ViewModel.TypeDosenViewModel

<div class="modal-body">
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.kode_type_dosen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kode_type_dosen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.deskripsi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.deskripsi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.is_active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.is_active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.updated_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.updated_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.updated_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.updated_date)
        </dd>

    </dl>
</div>

<div class="modal-footer">
    <input type="button" value="Edit" title="Edit" class="btn btn-primary" id="btn_details_edit" data-id="@Html.DisplayFor(model => model.id_type_dosen_pk)" />
    <input type="button" value="Cancel" title="Cancel" class="btn btn-default" id="btn_create_cancel" data-dismiss="modal" />
</div>

<script>
    $("#btn_details_edit").click(function () {
        $(".modal-title").html("Edit Form Jenis Karyawan");
        $(".div-bind-content").html(progHtml);

        $.ajax({
            url: '@Url.Action("Edit", "TypeDosen")',
            type: 'get',
            data: { paramId: $(this).attr("data-id") },
            success: function (result) {
                $(".div-bind-content").html(result);
            }
        });

    });
</script>

01.Materi.University.Web/Views/TypeDosen/Edit.cshtml
@model _03.Materi.University.ViewModel.TypeDosenViewModel

<div class="modal-body">
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_type_dosen_pk)

        <div class="form-group">
            @Html.LabelFor(model => model.kode_type_dosen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kode_type_dosen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kode_type_dosen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.deskripsi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.deskripsi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.deskripsi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.is_active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.is_active)
                @Html.ValidationMessageFor(model => model.is_active, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
</div>

<div class="modal-footer">
    <input type="button" value="Save" title="Save" class="btn btn-primary" id="btn_edit_save" />
    <input type="button" value="Cancel" title="Cancel" class="btn btn-default" id="btn_edit_cancel" data-dismiss="modal" />
</div>

<script>
    $("#btn_edit_save").click(function () {
        var item = {
            id_type_dosen_pk: $("#id_type_dosen_pk").val(),
            kode_type_dosen: $("#kode_type_dosen").val().toUpperCase(),
            deskripsi: $("#deskripsi").val(),
            is_active: $("#is_active").is(":checked")
        };

        $.ajax({
            url: '@Url.Action("Edit", "TypeDosen")',
            type: 'post',
            data: { paramModel: item },
            success: function (result) {
                if (result.success) {
                    $("#modal-edit-form").modal("hide");
                    ShowList();
                }
                else {
                    alert(result.message);
                }
            }
        });
    });
</script>

01.Materi.University.Web/Views/TypeDosen/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Master Data Jenis Karyawan</h4>

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">

            <button typeof="button" id="btn-add-type-dosen" class="btn btn-success" title="Create New">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Tambah Data
            </button>

        </div>
        <div class="panel-body">

            <div id="table-list">
                <div class="progress progress-striped active" style="margin-bottom:0">
                    <div class="progress-bar" style="width:100%" />
                </div>
            </div>

        </div>
    </div>
</div>


<div id="modal-edit-form" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
            </div>

            <div class="div-bind-content">
                @*berisikan konten body dan footer*@
            </div>

        </div>

    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        var progHtml = '<div class="progress progress-striped active" style="margin-bottom:0"><div class="progress-bar" style="width:100%"/></div>';

        $(document).ready(function () {
            ShowList();
        });

        function ShowList() {
            $("#table-list").html(progHtml);

            $.ajax({
                url: '@Url.Action("List","TypeDosen")',
                type: 'get',
                success: function (result) {
                    $("#table-list").html(result);
                }
            });
        }

        $("#btn-add-type-dosen").click(function () {
            /* Configurations Modal */
            $("#modal-edit-form").modal("show");
            $(".modal-title").html("Edit Form Jenis Karyawan");
            $(".div-bind-content").html(progHtml);

            /* Show body modal */
            $.ajax({
                url: '@Url.Action("Create","TypeDosen")',
                type: 'get',
                success: function (result) {
                    $(".div-bind-content").html(result);
                }
            })
        });

    </script>
}

01.Materi.University.Web/Views/TypeDosen/List.cshtml
@model IEnumerable<_03.Materi.University.ViewModel.TypeDosenViewModel>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.kode_type_dosen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.deskripsi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.is_active)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.created_by)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.created_date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.updated_by)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.updated_date)
        </th>
        <th></th>
    </tr>

    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.kode_type_dosen)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.deskripsi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.is_active)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.created_by)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.created_date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.updated_by)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.updated_date)
                </td>
                <td>
                    <button title="Edit" class="btn_grid_edit btn btn-warning" data-id="@item.id_type_dosen_pk">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    </button>
                    <button title="Delete" class="btn_grid_details btn btn-info" data-id="@item.id_type_dosen_pk">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                    </button>
                </td>
            </tr>
        }
    }

</table>


<script type="text/javascript">

    $(".btn_grid_edit").click(function () {
        //alert('Id nya adalah :' + $(this).attr("data-id"));
        $("#modal-edit-form").modal("show");
        $(".modal-title").html("Edit Form Jenis Karyawan");
        $(".div-bind-content").html(progHtml);

        $.ajax({
            url: '@Url.Action("Edit", "TypeDosen")',
            type: 'get',
            data: { paramId: $(this).attr("data-id") },
            success: function (result) {
                $(".div-bind-content").html(result);
            }
        });
    });

    $(".btn_grid_details").click(function () {
        //alert('Id nya adalah :' + $(this).attr("data-id"));
        $("#modal-edit-form").modal("show");
        $(".modal-title").html("Details Jenis Karyawan");
        $(".div-bind-content").html(progHtml);

        $.ajax({
            url: '@Url.Action("Details", "TypeDosen")',
            type: 'get',
            data: { paramId: $(this).attr("data-id") },
            success: function (result) {
                $(".div-bind-content").html(result);
            }
        });
    });

</script>